feature: attach-t0-prefix list, detach-t0-prefix-list
vmware/python-client-for-vmware-cloud-on-aws pull request #38
Opened 2021-09-18 01:40 UTC by fr0gger03

**New features:** 
- _attach-t0-prefix-list_: this will attach a specified prefix list to either the in_route_filter or the out_route_filter for the specified T0 BGP neighbor
- _detach-t0-prefix-lists_: this will detach all prefix lists from the the specified T0 BGP neighbor

tested on existing test SDDC

Signed-off-by: Tom Twyman <ttwyman@vmware.com>

2021-09-18 18:55 UTC, kremerpatrick requested changes
Nice additions! Little rework for the system property skipping but other than that looks good.

2021-09-18 18:55 UTC, kremerpatrick commented on pyVMC.py
> +        del neighbor_json['_revision']
When hidden properties are skipped in this manner, it introduces future bugs when an additional hidden property gets added. Consider looping with a for loop and deleting properties that start with '_'

2021-09-18 18:55 UTC, kremerpatrick commented on pyVMC.py
> +        del neighbor_json['_revision']
When hidden properties are skipped in this manner, it introduces future bugs when an additional hidden property gets added. Consider looping with a for loop and deleting properties that start with '_'

2021-09-19 13:36 UTC, fr0gger03 commented
Thanks - should be fixed. Please check it

2021-09-19 16:29 UTC, kremerpatrick approved these changes
LGTM

2021-09-19 16:29 UTC, merged