Feature: support for creation, deletion, modification of network segm…
vmware/python-client-for-vmware-cloud-on-aws pull request #89
Opened 2022-07-13 21:54 UTC by fr0gger03

…ents and T1 gateways from 1.18 onwards.

Includes new commands for:
configure-t1
remove t1
new-segment
configure-segment
remove-segment

To support bot 'fixed' segments (pre-1.18) and 'moveable' T1 and segments (1.18 and later).

Signed-off-by: Tom Twyman <ttwyman@vmware.com>

2022-07-14 19:47 UTC, kremerpatrick requested changes

2022-07-14 19:47 UTC, kremerpatrick commented on pyVMC.py
> +    json_data = {"type": kwargs["t1type"]}
We should do some argument validation since a user mistake in t1 type will result in an API failure.

2022-07-15 19:31 UTC, kremerpatrick requested changes

2022-07-15 19:31 UTC, kremerpatrick commented on pyVMC.py
> +        print(i, j)
Is this debugging or intentional?

2022-07-15 19:31 UTC, kremerpatrick commented on pyVMC.py
> +    configure_segment_json(proxy, session_token, segment_path, json_data)
I don't see where this one was changed like the others were - no return value?

2022-07-15 19:39 UTC, fr0gger03 commented
AHHH! debugging.


Tom Twyman
***@***.***
804-921-2705

 
 

Sent: Friday, July 15, 2022 at 3:31 PM
From: "Patrick Kremer" ***@***.***>
To: "vmware/python-client-for-vmware-cloud-on-aws" ***@***.***>
Cc: "Tom Twyman" ***@***.***>, "Author" ***@***.***>
Subject: Re: [vmware/python-client-for-vmware-cloud-on-aws] Feature: support for creation, deletion, modification of network segm… (PR #89)


 

@kremerpatrick requested changes on this pull request.


In pyVMC.py:

> +    for i, j in kwargs.items():
+        print(i, j)


Is this debugging or intentional?


In pyVMC.py:

> +    keep_list = ['display_name', 'connectivity_path','advanced_config','type']
+    # Construct a new JSON using just the keys we want to keep
+    json_data = dict([(key, val) for key, val in
+           json_init.items() if key in keep_list])
+    # Update the json_data with the configuration specified by the user.
+    if kwargs['connectivity'] is not None:
+        json_data["advanced_config"]["connectivity"] = f'{kwargs["connectivity"]}'
+    if kwargs['routing_type'] is not None:
+        json_data["type"] = f'{kwargs["routing_type"]}'
+    if kwargs['tier1_id'] is not None:
+        if segment_path == "/infra/tier-1s/cgw":
+            print("This is a fixed segment - you may not alter the connectivity path.  Plese create a 'moveable' segment.")
+        else:
+            json_data["connectivity_path"] = f'/infra/tier-1s/{kwargs["tier1_id"]}'
+    # make the call to the API
+    configure_segment_json(proxy, session_token, segment_path, json_data)


I don't see where this one was changed like the others were - no return value?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-07-15 20:57 UTC, kremerpatrick approved these changes

2022-07-15 20:57 UTC, merged